sonar.projectKey=python-sample-1
sonar.projectName=Python Sample 1
sonar.projectVersion=1.0

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=test_*.py

sonar.python.coverage.reportPaths=coverage.xml
